spring:
   application:
      name: security_hn_jv2311229
   datasource:
      url: jdbc:mysql://localhost:3306/security_6?createDatabaseIfNotExist=true
      username: root
      password: 123456
   jooq:
      sql-dialect: org.hibernate.dialect.MySQL8Dialect
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            show_sql: true
            format_sql: true

# jwt
jwt:
   secret_key: rikkei_academy
   expired:
      access: 864000